# script to generate precision recalls of ukbb/gtex variants using sklearn
#%%
# import packages
import pandas as pd
import os
from tqdm import tqdm
import torch
import matplotlib.pyplot as mpl
import seaborn as sns
import numpy as np
from sklearn import metrics
from scipy import stats
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import PrecisionRecallDisplay
#%%
# Open GTEx PRC Dataframe as generated by Jacob's R Script -  only SNPs
gtex_prc_df = pd.read_csv('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/final_datasets/gtex.paired.mpra.prc.snps.malinois.cells.txt',
                          sep = '\t')
# Open Traits PRC Dataframe as generated by Jacob's R Script - only SNPs
traits_prc_df = pd.read_csv('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/final_datasets/traits.paired.mpra.prc.snps.malinois.cells.txt',
                            sep = '\t')
#%%
# define function to return DF of Precision and Recall of Experimental for CRE, emVar, and emVar + CRE
def empirical_precision_recall (df, library):
    # make binary list of true positives
    causal_true_false = [1 if i == True else 0 for i in df['causal']]
    # CRE
    # make list of hits/misses
    cre_hit_miss = [1 if i == 1 else 0 for i in df['CRE']]
    # calculate precision
    cre_precision = precision_score(causal_true_false,
                                    cre_hit_miss)
    # calculate recall
    cre_recall = recall_score(causal_true_false,
                              cre_hit_miss)
    # emVar
    # make list of hits/misses
    emvar_hit_miss = [1 if i == True else 0 for i in df['emVar_any']]
    # calculate precision
    emvar_precision = precision_score(causal_true_false,
                                      emvar_hit_miss)
    # calculate recall
    emvar_recall = recall_score(causal_true_false,
                                emvar_hit_miss)
    # emVar + CRE
    # make list of hits/misses
    emvar_cre_hit_miss = [1 if i == True and j == 1 else 0 for i,j in zip(df['emVar_any'],
                                                                          df['CRE'])]
    # calculate precision
    emvar_cre_precision = precision_score(causal_true_false,
                                          emvar_cre_hit_miss)
    # calculate recall
    emvar_cre_recall = recall_score(causal_true_false,
                                    emvar_cre_hit_miss)
    # make a DataFrame of Precision and Recall by Category
    prc_df = pd.DataFrame({'category' : [f'{library}: CRE', f'{library}: emVar', f'{library}: emVar + CRE'],
                           'precision' : [cre_precision, emvar_precision, emvar_cre_precision],
                           'recall' : [cre_recall, emvar_recall, emvar_cre_recall]})
    return prc_df
#%%
# Define functions for parsing raw predictions
def splitter (string):
    split = string[1:-1].split(',')
    float_split = [float(i) for i in split]
    return float_split
# define function to convert pt to DF
def pt2df (path2pt, n_preds):
    # Open predictions
    pt = torch.load(path2pt)
    # Open VCF used for generateing predictions
    vcf = pt['vcf']
    # Use VCF to generate collapsed IDs chr:pos:ref:alt:INFO
    vcf_ids = [(':').join([i,str(j),k,l]) for i,j,k,l in zip(vcf['chrom'],
                                                             vcf['pos'],
                                                             vcf['ref'],
                                                             vcf['alt'])]
    # Make Dictionary of ID:number (basically index) pairs
    id_dict = dict(zip(vcf_ids, [i for i in range(0,len(vcf_ids))]))
    # Iterate over Dictionary to combine ID from VCF with predictions from Tensor
    df_rows = []
    for i in tqdm(id_dict):
        tmp = []
        # Split ID back into Chrom, Pos, Ref, Alt
        splitted = i.split(':')
        chrom = splitted[0]
        pos = splitted[1]
        ref = splitted[2]
        alt = splitted[3]
        # Make a tmp list for ref/alt each cell type
        # K562
        k562_ref_list = []
        k562_alt_list = []
        # HepG2
        hepg2_ref_list = []
        hepg2_alt_list = []
        # SK-N-SH
        sknsh_ref_list = []
        sknsh_alt_list = []
        # Iterate of each prediction
        for x in range(0, n_preds):
            # Get reference for predictions for MEAN F/R and rev strands
            ref_pred = pt['ref'][id_dict.get(i), 0, x]
            ref_rev_comp = pt['ref'][id_dict.get(i), 1, x]
            # Take average of MEAN F/R/rev_comp predictions and add to cell type list
            k562_ref_list.append((sum([ref_pred[0], ref_rev_comp[0]])/2).item())
            hepg2_ref_list.append((sum([ref_pred[1], ref_rev_comp[1]])/2).item())
            sknsh_ref_list.append((sum([ref_pred[2], ref_rev_comp[2]])/2).item())
            # Get alternate predictions for MEAN F/R and rev strands
            alt_pred = pt['alt'][id_dict.get(i), 0, x]
            alt_rev_comp = pt['alt'][id_dict.get(i), 1, x]
            # Take average of MEAN F/R/rev_comp predictions and add to cell type list
            k562_alt_list.append((sum([alt_pred[0], alt_rev_comp[0]])/2).item())
            hepg2_alt_list.append((sum([alt_pred[1], alt_rev_comp[1]])/2).item())
            sknsh_alt_list.append((sum([alt_pred[2], alt_rev_comp[2]])/2).item())
        # Subtract alt-ref to get skew
        k562_skew = [j-i for i,j in zip(k562_ref_list, k562_alt_list)]
        hepg2_skew = [j-i for i,j in zip(hepg2_ref_list, hepg2_alt_list)]
        sknsh_skew = [j-i for i,j in zip(sknsh_ref_list, sknsh_alt_list)]
        # Build row as tmp list
        tmp.append(chrom)
        tmp.append(pos)
        tmp.append(ref)
        tmp.append(alt)
        tmp.append(k562_ref_list)
        tmp.append(k562_alt_list)
        tmp.append(hepg2_ref_list)
        tmp.append(hepg2_alt_list)
        tmp.append(sknsh_ref_list)
        tmp.append(sknsh_alt_list)
        tmp.append(k562_skew)
        tmp.append(hepg2_skew)
        tmp.append(sknsh_skew)
        # Append tmp list to "rows" list for formatting to DF
        df_rows.append(tmp)
    col_names = ['chrom',
                 'pos',
                 'ref',
                 'alt',
                 'k562_ref_pred',
                 'k562_alt_pred',
                 'hepg2_ref_pred',
                 'hepg2_alt_pred',
                 'sknsh_ref_pred',
                 'sknsh_alt_pred',
                 'k562_skew_pred',
                 'hepg2_skew_pred',
                 'sknsh_skew_pred']
    df = pd.DataFrame(df_rows, columns=col_names)
    return df
def pt2df_dict (path2pts, n_preds):
    df_dict = {}
    pt_list = [i for i in os.listdir(path2pts) if i.endswith('.pt')]
    for i in pt_list:
        print(i)
        chr_key = i.split('_')[0]
        df_dict.update({chr_key : pt2df(f'{path2pts}/{i}', n_preds)})
    return df_dict
# define function to add max ref/alt activities for a prediction DF for easier acitivity filtering
def add_max_act (pred_df):
    # k562
    pred_df['k562_max_act'] = [max([i,j], key=abs) for i,j in zip(pred_df['k562_ref_pred'],
                                                                  pred_df['k562_alt_pred'])]
    # hepg2
    pred_df['hepg2_max_act'] = [max([i,j], key=abs) for i,j in zip(pred_df['hepg2_ref_pred'],
                                                                   pred_df['hepg2_alt_pred'])]
    # sknsh
    pred_df['sknsh_max_act'] = [max([i,j], key=abs) for i,j in zip(pred_df['sknsh_ref_pred'],
                                                                   pred_df['sknsh_alt_pred'])]
    return pred_df
# %%
# open ukbb/traits predictions - 18 step: end 180, start 9, step size 10, generated with dsub 0.1.7
traits_017_preds = pt2df_dict('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/ukbb_liftover/hg38_017_preds/', 
                              18)
# convert single prediction to float
col_names = ['k562_ref_pred', 'k562_alt_pred',
             'hepg2_ref_pred', 'hepg2_alt_pred',
             'sknsh_ref_pred', 'sknsh_alt_pred',
             'k562_skew_pred', 'hepg2_skew_pred', 'sknsh_skew_pred']
# Make DF with Average Predictions
# Traits
traits_017_avg_df = pd.concat(traits_017_preds.values())
for i in col_names:
    traits_017_avg_df.loc[:,][i] = [np.mean(j) for j in traits_017_avg_df[i]]
traits_017_avg_df.loc[:,]['id'] = [(':').join([i, str(j), k , l]) for i,j,k,l in zip(traits_017_avg_df['chrom'],
                                                                                     traits_017_avg_df['pos'],
                                                                                     traits_017_avg_df['ref'],
                                                                                     traits_017_avg_df['alt'])]
traits_017_avg_df = add_max_act(traits_017_avg_df)
# open gtex predictions - 18 step: end 180, start 9, step size 10, generated with dsub 0.1.7
gtex_017_preds = pt2df_dict('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/dsub_017/gtex_all_017/raw_preds/gtex_017_raw_preds/', 
                            18)
# Make DF with Average Predictions
# GTEx
gtex_017_avg_df = pd.concat(gtex_017_preds.values())
for i in col_names:
    gtex_017_avg_df.loc[:,][i] = [np.mean(j) for j in gtex_017_avg_df[i]]
gtex_017_avg_df.loc[:,]['id'] = [(':').join([i, str(j), k , l]) for i,j,k,l in zip(gtex_017_avg_df['chrom'],
                                                                                   gtex_017_avg_df['pos'],
                                                                                   gtex_017_avg_df['ref'],
                                                                                   gtex_017_avg_df['alt'])]
gtex_017_avg_df = add_max_act(gtex_017_avg_df)
# %%
### Merge Predictions with PRC Dataframes ###
# Add hg38 IDs to GTEx PRC DF
gtex_prc_df.loc[:,]['id'] = [(':').join([i.split('_')[0],
                                         i.split('_')[1],
                                         i.split('_')[2],
                                         i.split('_')[3]]) for i in gtex_prc_df['variant_hg38']]
# Add hg38 IDs to Traits
# open lifted IDs
hg38_ids_from_liftover = pd.read_csv('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/ukbb_liftover/traits_bed_hg38.bed',
                                    sep = '\t',
                                    header=None)
# make list of hg38 IDs
hg38_id = [(':').join([i, str(j), k.split(':')[-2], k.split(':')[-1]]) for i,j,k in zip(hg38_ids_from_liftover[0],
                                                                                        hg38_ids_from_liftover[1],
                                                                                        hg38_ids_from_liftover[3])]
# make a dictionary of hg19 ID : hg38 ID pairs
hg19_hg38_id_dict = dict(zip(hg38_ids_from_liftover[3],
                            hg38_id))
# match hg19 and hg38 ids to add column to DF
hg38_matched_list = [hg19_hg38_id_dict.get(i) for i in traits_prc_df['variant']]
traits_prc_df.loc[:,]['id'] = hg38_matched_list
# GTEx
# Average
gtex_017_average_merge = gtex_prc_df.merge(gtex_017_avg_df, how='inner', on='id')
# Traits
# Average
traits_017_avg_merge = traits_prc_df.merge(traits_017_avg_df, how='inner', on='id')
# %%
# make vcfs for generating SEI predictions for comparison
#gtex_prc_vcf = pd.DataFrame({'#CHROM' : [i.split('_')[0] for i in gtex_prc_df['variant_hg38']],
#                             'POS' : [i.split('_')[1] for i in gtex_prc_df['variant_hg38']],
#                             'ID' : ['.' for i in range(len(gtex_prc_df))],
#                             'REF' : [i.split('_')[2] for i in gtex_prc_df['variant_hg38']],
#                             'ALT' : [i.split('_')[3] for i in gtex_prc_df['variant_hg38']],
#                             'QUALITY' : ['.' for i in range(len(gtex_prc_df))],
#                             'FILTER' : ['.' for i in range(len(gtex_prc_df))],
#                             'INFO' : gtex_prc_df['causal']})
#traits_prc_vcf = pd.DataFrame({'#CHROM' : [i.split(':')[0] for i in traits_017_avg_merge['id']],
#                               'POS' : [i.split(':')[1] for i in traits_017_avg_merge['id']],
#                               'ID' : ['.' for i in range(len(traits_prc_df))],
#                               'REF' : [i.split(':')[2] for i in traits_017_avg_merge['id']],
#                               'ALT' : [i.split(':')[3] for i in traits_017_avg_merge['id']],
#                               'QUALITY' : ['.' for i in range(len(traits_017_avg_merge))],
#                               'FILTER' : ['.' for i in range(len(traits_017_avg_merge))],
#                               'INFO' : traits_017_avg_merge['causal']})
# save to disk
#gtex_prc_vcf.to_csv('gtex_prc_hg38_vars_for_SEI_preds.vcf',
#                    sep = '\t',
#                    index = False)
#traits_prc_vcf.to_csv('traits_prc_hg38_vars_for_SEI_preds.vcf',
#                      sep = '\t',
#                      index = False)
# %% 
# open sei preds
sei_dnase_preds = pd.read_csv('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/final_datasets/precision_recall/ukbb_gtex_prc_sei_dnase_preds_all_cell_types_dnase.tsv',
                              sep = '\t')
# get hepg2 and k562 columns for calculating precision recall
sei_pred_cols = [i for i in sei_dnase_preds.keys() if 'DNase' in i]
# get max prediction for each variant
maxCol = lambda x: max(x.min(), x.max(), key=abs)
sei_dnase_preds['sei_max_pred'] = sei_dnase_preds.filter(sei_pred_cols).apply(maxCol,
                                                              axis=1)
# add hg38 id to sei preds for merging with malinois preds
sei_dnase_preds['id'] = [(':').join([chrom,
                                     str(pos),
                                     ref,
                                     alt]) for chrom,
                                               pos,
                                               ref,
                                               alt in zip(sei_dnase_preds['chrom'],
                                                          sei_dnase_preds['pos'],
                                                          sei_dnase_preds['ref'],
                                                          sei_dnase_preds['alt'])]
# filter sei preds for gtex
gtex_sei = sei_dnase_preds[sei_dnase_preds['id'].isin(gtex_017_average_merge['id'])].drop_duplicates().filter(['id',
                                                                                                               'sei_max_pred'])
# fitler sei preds for ukbb
ukbb_sei = sei_dnase_preds[sei_dnase_preds['id'].isin(traits_017_avg_merge['id'])].drop_duplicates().filter(['id',
                                                                                                             'sei_max_pred'])
# merge with other datasets
all_gtex_merge = gtex_017_average_merge.merge(gtex_sei, on='id')
# add column for merging with deltaSVM
all_gtex_merge['delta_id'] = [(':').join(i.split(':')[:4]) for i in all_gtex_merge['ID']]
all_traits_merge = traits_017_avg_merge.merge(ukbb_sei, on='id')
# add column for merging with deltaSVM
all_traits_merge['delta_id'] = [(':').join(i.split(':')[:4]) for i in all_traits_merge['ID']]
# %%
# open deltaSVM predictions
# gtex
gtex_hepg2_deltaSVM = pd.read_csv('/Users/buttsj/JAX Dropbox/John Butts/Variant_Effects/ukbb_gtex_mpra/final_datasets/precision_recall/deltaSVM/2015_weights/gtex_hepg2_2015_weight_deltaSVM_preds.txt',
                                  sep = '\t',
                                  header = None,
                                  names = ['variant',
                                           'gtex_hepg2_deltaSVM'])
gtex_k562_deltaSVM = pd.read_csv('/Users/buttsj/JAX Dropbox/John Butts/Variant_Effects/ukbb_gtex_mpra/final_datasets/precision_recall/deltaSVM/2015_weights/gtex_k562_2015_weight_deltaSVM_preds.txt',
                                 sep = '\t',
                                 header = None,
                                 usecols=[1],
                                 names = ['gtex_k562_deltaSVM'])
#%%
#all_gtex_mods_delta_svm = pd.read_csv('/Users/buttsj/Dropbox (JAX)/Variant_Effects/ukbb_gtex_mpra/final_datasets/precision_recall/deltaSVM/all_gtex_prc_deltaSVM_preds_2019_weights.tsv',
#                                      sep = '\t')
#all_gtex_mod_cols = [i for i in all_gtex_mods_delta_svm.keys() if i != 'variant']
# get max prediction for each variant
#maxCol = lambda x: max(x.min(), x.max(), key=abs)
#all_gtex_mods_delta_svm['max_deltaSVM'] = all_gtex_mods_delta_svm.filter(all_gtex_mod_cols).apply(maxCol,
#                                                              axis=1)
#%%
# hepg2
ukbb_hepg2_deltaSVM = pd.read_csv('/Users/buttsj/JAX Dropbox/John Butts/Variant_Effects/ukbb_gtex_mpra/final_datasets/precision_recall/deltaSVM/2015_weights/ukbb_hepg2_2015_weight_deltaSVM_preds.txt',
                                  sep = '\t',
                                  header = None,
                                  names = ['variant',
                                           'ukbb_hepg2_deltaSVM'])
ukbb_k562_deltaSVM = pd.read_csv('/Users/buttsj/JAX Dropbox/John Butts/Variant_Effects/ukbb_gtex_mpra/final_datasets/precision_recall/deltaSVM/2015_weights/ukbb_k562_2015_weight_deltaSVM_preds.txt',
                                 sep = '\t',
                                 header = None,
                                 usecols=[1],
                                 names = ['ukbb_k562_deltaSVM'])
# combine deltaSVM predictions into single DF
# gtex
all_gtex_deltaSVM = pd.concat([gtex_hepg2_deltaSVM,
                               gtex_k562_deltaSVM], axis=1, join='outer')
# add a max column for hepg2/k562
all_gtex_deltaSVM['max_deltaSVM'] = [max([k, h], key=abs) for h,k in zip(all_gtex_deltaSVM['gtex_hepg2_deltaSVM'],
                                                                         all_gtex_deltaSVM['gtex_k562_deltaSVM'])]
# ukbb
all_ukbb_deltaSVM = pd.concat([ukbb_hepg2_deltaSVM,
                               ukbb_k562_deltaSVM], axis=1, join='outer')
# add a max column for hepg2/k562
all_ukbb_deltaSVM['max_deltaSVM'] = [max([k, h], key = abs) for h,k in zip(all_ukbb_deltaSVM['ukbb_hepg2_deltaSVM'],
                                                                           all_ukbb_deltaSVM['ukbb_k562_deltaSVM'])]
# %%
# add deltaSVM predictions to DF
# gtex
all_gtex_with_svm = all_gtex_merge.merge(all_gtex_deltaSVM, left_on='delta_id', right_on='variant')
# ukbb
all_traits_with_svm = all_traits_merge.merge(all_ukbb_deltaSVM, left_on='delta_id', right_on='variant')
# %% define palette for plotting
# get information for tab20c palette
tab20c = sns.color_palette('tab20c').as_hex()
tab20b = sns.color_palette('tab20b').as_hex()
# GTeX
gtex_palette = {'MPAC' : '#9ecae1',
                'MPAC + CRE' : '#3182bd',
                'emVar' : '#3DB371',
                'emVar + CRE' : '#196533',
                'SEI DNase' : '#fd8d3c',
                'SEI + CRE' : '#e6550d',
                'deltaSVM' : '#e7ba52',
                'deltaSVM + CRE' : 'darkgoldenrod',
                'CADD' : '#31a354',
                'CADD v1.4' : 'red'}
traits_palette = {'MPAC' : '#9ecae1',
                'MPAC + CRE' : '#3182bd',
                'emVar' : '#3DB371',
                'emVar + CRE' : '#196533',
                'SEI DNase' : '#fd8d3c',
                'SEI + CRE' : '#e6550d',
                'deltaSVM' : '#e7ba52',
                'deltaSVM + CRE' : 'darkgoldenrod',
                'CADD' : '#31a354',
                'CADD v1.4' : 'red'}
# %%
# define function for calculating prc with sklearn 
def sklearn_precision_recall (merge_df,
                              cohort,
                              palette_dict,
                              ylim,
                              title,
                              save_fig,
                              sum_df2save):
    # annotate empirical true/false
    merge_df['emp_true'] = [1 if i == True else 0 for i in merge_df['causal']]
    # get positive df
    #pos_df = merge_df[merge_df['emp_true'] == 1]
    #neg_df = merge_df[merge_df['emp_true'] == 0].sample(len(pos_df))
    # recombine
    #merge_df = pd.concat([pos_df, neg_df])
    # calculate empirical precision recall
    emp_prc = empirical_precision_recall(merge_df,
                                         cohort)
    ### no activity threshold ###
    # get max of hepg2, k562, sknsh skew
    merge_df['no_act_abs_max'] = [abs(max([k,
                                           h,
                                           s], key=abs)) for k,h,s in zip(merge_df['k562_skew_pred'],
                                                                          merge_df['hepg2_skew_pred'],
                                                                          merge_df['sknsh_skew_pred'])]
    # calculate precision recall
    no_act_pre, no_act_rec, no_act_thresh = precision_recall_curve(merge_df['emp_true'],
                                                                   merge_df['no_act_abs_max'])
    no_act_auc = metrics.auc(no_act_rec,
                             no_act_pre)
    # make df for plotting
    no_act2plot = pd.DataFrame({'precision' : no_act_pre,
                                'recall' : no_act_rec,
                                'feature' : ['MPAC' for i in range(len(no_act_pre))],
                                'cohort' : [cohort for i in range(len(no_act_pre))]})
    # calculate no activity + CRE curve
    # refactor skew to account for CRE
    merge_df['no_act_cre_refactor'] = [skew if cre == 1 else 0 for skew, cre in zip(merge_df['no_act_abs_max'],
                                                                                    merge_df['CRE'])]
    # calculate precision recall
    no_act_cre_pre, no_act_cre_rec, no_act_cre_thresh = precision_recall_curve(merge_df['emp_true'],
                                                                               merge_df['no_act_cre_refactor'])
    # drop position so that we don't get line out to 1, .5
    no_act_cre_pre = no_act_cre_pre[1:]
    no_act_cre_rec = no_act_cre_rec[1:]
    no_act_cre_auc = metrics.auc(no_act_cre_rec,
                                 no_act_cre_pre)
    # make df for plotting
    no_act_cre2plot = pd.DataFrame({'precision' : no_act_cre_pre,
                                    'recall' : no_act_cre_rec,
                                    'feature' : ['MPAC + CRE' for i in range(len(no_act_cre_pre))],
                                    'cohort' : [cohort for i in range(len(no_act_cre_pre))]})
    # calculate sei prc
    # take absolute value of sei predictions
    merge_df['sei_abs_max'] = [abs(i) for i in merge_df['sei_max_pred']]
    sei_pre, sei_rec, sei_thresh = precision_recall_curve(merge_df['emp_true'],
                                                          merge_df['sei_abs_max'])
    sei_auc = metrics.auc(sei_rec,
                          sei_pre)
    sei2plot = pd.DataFrame({'precision' : sei_pre,
                             'recall' : sei_rec,
                             'feature' : ['SEI DNase' for i in range(len(sei_pre))],
                             'cohort' : [cohort for i in range(len(sei_pre))]})
    # calculate sei + CRE prc
    merge_df['sei_cre_refactor'] = [sei_skew if cre == 1 else 0 for sei_skew, cre in zip(merge_df['sei_abs_max'],
                                                                                         merge_df['CRE'])]
    # calculate precision recall
    sei_cre_pre, sei_cre_rec, sei_cre_thresh = precision_recall_curve(merge_df['emp_true'],
                                                                      merge_df['sei_cre_refactor'])
    # drop position so that we don't get line out to 1, .5
    sei_cre_pre = sei_cre_pre[1:]
    sei_cre_rec = sei_cre_rec[1:]
    sei_cre_auc = metrics.auc(sei_cre_rec,
                              sei_cre_pre)
    sei_cre2plot = pd.DataFrame({'precision' : sei_cre_pre,
                                 'recall' : sei_cre_rec,
                                 'feature' : ['SEI + CRE' for i in range(len(sei_cre_pre))],
                                 'cohort' : [cohort for i in range(len(sei_cre_pre))]})
    # calculate deltaSVM prc
    # take absolute value of deltaSVM predictions
    merge_df['deltaSVM_abs_max'] = [abs(i) for i in merge_df['max_deltaSVM']]
    deltaSVM_pre, deltaSVM_rec, deltaSVM_thresh = precision_recall_curve(merge_df['emp_true'],
                                                                         merge_df['deltaSVM_abs_max'])
    deltaSVM_auc = metrics.auc(deltaSVM_rec,
                               deltaSVM_pre)
    deltaSVM2plot = pd.DataFrame({'precision' : deltaSVM_pre,
                                  'recall' : deltaSVM_rec,
                                  'feature' : ['deltaSVM' for i in range(len(deltaSVM_pre))],
                                  'cohort' : [cohort for i in range(len(deltaSVM_pre))]})
    # calculate deltaSVM + CRE prc
    merge_df['deltaSVM_cre_refactor'] = [svm_skew if cre == 1 else 0 for svm_skew, cre in zip(merge_df['deltaSVM_abs_max'],
                                                                                              merge_df['CRE'])]
    svm_cre_pre, svm_cre_rec, svm_cre_thresh = precision_recall_curve(merge_df['emp_true'],
                                                                      merge_df['deltaSVM_cre_refactor'])
    # drop first position to end line at CRE
    svm_cre_pre = svm_cre_pre[1:]
    svm_cre_rec = svm_cre_rec[1:]
    svm_cre_auc = metrics.auc(svm_cre_rec,
                              svm_cre_pre)
    svm_cre2plot = pd.DataFrame({'precision' : svm_cre_pre,
                                 'recall' : svm_cre_rec,
                                 'feature' : ['deltaSVM + CRE' for i in range(len(svm_cre_rec))],
                                 'cohort' : [cohort for i in range(len(svm_cre_rec))]})
    # make a df for saving aucs and data descriptions (n positive/negative, total vars, etc) to disk
    summary_df = pd.DataFrame({'library' : [cohort],
                               'n_vars' : [len(merge_df)],
                               'n_causal' : [merge_df['emp_true'].tolist().count(1)],
                               'n_benign' : [merge_df['emp_true'].tolist().count(0)],
                               'no_act_auc' : [no_act_auc],
                               'no_act_cre_auc' : [no_act_cre_auc],
                               'sei_auc' : [sei_auc],
                               'sei_cre_auc' : [sei_cre_auc],
                               'deltaSVM_auc' : [deltaSVM_auc],
                               'deltaSVM_cre_auc' : [svm_cre_auc]})
    print(summary_df)
    # save summary df to file
    #summary_df.to_csv(sum_df2save,
    #                  sep = '\t',
    #                  index = False)
    # plot PRC
    all2plot = pd.concat([no_act2plot,
                          no_act_cre2plot,
                          sei2plot,
                          sei_cre2plot,
                          deltaSVM2plot,
                          svm_cre2plot])
    mpl.figure(dpi=300)
    mpl.rcParams['pdf.fonttype'] = 42
    mpl.rcParams['ps.fonttype'] = 42
    sns.lineplot(data=all2plot,
                 x='recall',
                 y='precision',
                 hue='feature',
                 palette=palette_dict,
                 errorbar=None,
                 alpha=.75)
    mpl.xlabel('Recall')
    mpl.ylabel('Precision')
    # add empirical annotations
    # CRE
    sns.scatterplot(data=emp_prc[emp_prc.index == 0],
                    x='recall',
                    y='precision',
                    hue='category',
                    linewidth=0,
                    marker='s',
                    s=50)
    # emVar
    sns.scatterplot(data=emp_prc[emp_prc.index == 1],
                    x='recall',
                    y='precision',
                    hue='category',
                    linewidth=0,
                    marker='^',
                    s=50)
    # emVar + CRE
    sns.scatterplot(data=emp_prc[emp_prc.index == 2],
                    x='recall',
                    y='precision',
                    hue='category',
                    linewidth=0,
                    s=50)
    mpl.hlines(y=.5,
               xmin=0,
               xmax=1,
               color='k',
               linestyle='dashed')
    mpl.ylim(ylim)
    mpl.title(title)
    sns.despine()
    #mpl.savefig(save_fig)
    # calculate precision for MPAC at empirical recall levels for emVars and emVar + CRE
    # emVar alone
    emp_recall_emvar = emp_prc[emp_prc.index == 1]['recall'].tolist()[0]
    # calculate precision at that recall for MPAC
    mpac_pre_at_emp_rec = [i for i,j in zip(no_act_pre, no_act_rec) if j == emp_recall_emvar][0]
    print(f'MPAC Precision at empirical emVar recall: {mpac_pre_at_emp_rec}')
    # emVar + CRE
    emp_recall_emvar_cre = emp_prc[emp_prc.index == 2]['recall'].tolist()[0]
    # calculate precision at that recall for MPAC + CRE
    mpac_pre_at_emp_cre_rec = [i for i,j in zip(no_act_cre_pre, no_act_cre_rec) if j == emp_recall_emvar_cre][0]
    print(f'MPAC Precision at empirical emVar + CRE recall: {mpac_pre_at_emp_cre_rec}')
    #mpac_pre_at_emp_rec = no_act_pre[mpac_pre_at_emp_rec_idx]
    #print(np.mean(no_act))
    #print(mpac_pre_at_emp_rec)
    return merge_df, emp_prc;
# %% 
# calculate empirical precision and recall
# gtex
#gtex_empirical_prc = empirical_precision_recall(all_gtex_merge, 'GTEx')
# ukbb
#ukbb_empirical_prc = empirical_precision_recall(all_traits_merge, 'Complex Traits')
### moved empirical prc calculation into full prc function ###
# %% 
# plot GTeX - no activity filter
gtex_prc_df, gtex_emp_prc = sklearn_precision_recall(all_gtex_with_svm,
                         'GTex',
                         gtex_palette,
                         (.2,1),
                         'Precision Recall of Fine-Mapped Variants: GTex',
                         '/Users/buttsj/Dropbox (JAX)/Variant_Effects/final_plots_v2/fig_1/gtex_sklearn_prc_no_act_filter_no_svm.pdf',
                         '/Users/buttsj/Dropbox (JAX)/Variant_Effects/final_plots_v2/fig_1/gtex_prc_summary_v4.txt')
# %%
# plot UKBB - no activity filter
ukbb_prc_df, ukbb_emp_prc = sklearn_precision_recall(all_traits_with_svm,
                         'UKBB',
                         traits_palette,
                         (.45,1.01),
                         'Precision Recall of Fine-Mapped Variants: UKBB',
                         '/Users/buttsj/Dropbox (JAX)/Variant_Effects/final_plots_v2/fig_2/ukbb_sklearn_prc_no_act_filter_no_sei.pdf',
                         '/Users/buttsj/Dropbox (JAX)/Variant_Effects/final_plots_v2/fig_2/ukbb_prc_summary_v4.txt')
# %%
